# -*- coding: utf-8 -*-
"""웹사이트 제작 코드.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8WKOaFfZCFeF8-W27SHUXf9yrukCYKS
"""

import os
from flask import Flask, render_template_string, request, redirect, url_for, session
import streamlit as st


# ==========================================
# 1. 설정 (비밀번호 및 보안키)
# ==========================================
app = Flask(__name__)
app.secret_key = 'secret_key_1234'  # 세션 암호화 키 (변경 가능)
ACCESS_PASSWORD = "team2026"        # 🔐 접속 비밀번호

# ==========================================
# 2. 데이터 (GPT 도구 목록)
# ==========================================
gpt_tools = [
    {
        "category": "📝 문서/작문",
        "name": "비즈니스 이메일 봇",
        "desc": "상황만 말하면 격식 있는 메일 초안을 작성해줍니다.",
        "link": "https://chatgpt.com/",
        "prompt": "상황: [거래처에 단가 인상 요청].\n톤앤매너: 정중하지만 단호하게.\n위 내용으로 이메일 초안 작성해줘."
    },
    {
        "category": "📊 업무 효율",
        "name": "회의록 3줄 요약기",
        "desc": "녹취록이나 메모를 넣으면 핵심 내용과 할 일을 정리합니다.",
        "link": "https://chatgpt.com/",
        "prompt": "다음 회의 내용을 요약하고, 담당자별 Action Item을 표로 정리해줘."
    },
    {
        "category": "💡 아이디어",
        "name": "마케팅 카피라이터",
        "desc": "상품 특징을 입력하면 블로그/인스타용 홍보 문구를 뽑아줍니다.",
        "link": "https://chatgpt.com/",
        "prompt": "2030 직장인을 타겟으로 한 '거북목 교정기' 인스타그램 홍보 문구 5개 추천해줘."
    }
]

# ==========================================
# 3. HTML 화면 디자인 (CSS 포함)
# ==========================================
HTML_TEMPLATE = """
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Smart Work Portal</title>
    <style>
        body { font-family: 'Pretendard', sans-serif; background-color: #f4f6f8; margin: 0; padding: 20px; color: #333; }
        .container { max-width: 800px; margin: 0 auto; }

        /* 로그인 화면 */
        .login-box { background: white; padding: 40px; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); text-align: center; max-width: 400px; margin: 100px auto; }
        input[type="password"] { width: 100%; padding: 12px; margin-top: 10px; border: 1px solid #ddd; border-radius: 8px; box-sizing: border-box; }

        /* 메인 화면 */
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .btn { padding: 8px 16px; border-radius: 6px; border: none; cursor: pointer; font-weight: bold; text-decoration: none; display: inline-block; }
        .btn-primary { background-color: #3b82f6; color: white; }
        .btn-danger { background-color: #ef4444; color: white; }
        .btn-copy { background-color: #e5e7eb; color: #333; font-size: 13px; margin-right: 5px; }

        .card { background: white; padding: 20px; border-radius: 12px; margin-bottom: 16px; box-shadow: 0 2px 10px rgba(0,0,0,0.03); }
        .badge { display: inline-block; background: #eff6ff; color: #1d4ed8; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; margin-bottom: 8px; }
        .desc { color: #666; font-size: 14px; margin: 5px 0 15px 0; }
        textarea { width: 100%; height: 60px; padding: 10px; border: 1px solid #eee; border-radius: 8px; background: #fafafa; color: #555; resize: none; font-size: 13px; box-sizing: border-box; margin-bottom: 10px; }
    </style>
    <script>
        function copyText(id) {
            var copyText = document.getElementById(id);
            copyText.select();
            document.execCommand("copy");
            alert("프롬프트가 복사되었습니다!");
        }
    </script>
</head>
<body>
    {% if not session.get('authenticated') %}
    <!-- 로그인 화면 -->
    <div class="login-box">
        <h2>🔒 접속 권한 인증</h2>
        <p>사내 코드를 입력해주세요.</p>
        <form method="POST" action="/login">
            <input type="password" name="password" placeholder="비밀번호 입력" required>
            <button type="submit" class="btn btn-primary" style="width:100%; margin-top:15px; padding:12px;">로그인</button>
        </form>
        {% if error %}<p style="color:red; font-size:13px; margin-top:10px;">{{ error }}</p>{% endif %}
    </div>

    {% else %}
    <!-- 메인 화면 -->
    <div class="container">
        <div class="header">
            <h2>🚀 AI담당관 업무비서</h2>
            <form method="POST" action="/logout" style="margin:0;">
                <button type="submit" class="btn btn-danger">로그아웃</button>
            </form>
        </div>

        {% for tool in tools %}
        <div class="card">
            <span class="badge">{{ tool.category }}</span>
            <h3 style="margin: 5px 0;">{{ tool.name }}</h3>
            <p class="desc">{{ tool.desc }}</p>

            <textarea id="p{{ loop.index }}" readonly>{{ tool.prompt }}</textarea>

            <div style="text-align: right;">
                <button class="btn btn-copy" onclick="copyText('p{{ loop.index }}')">프롬프트 복사</button>
                <a href="{{ tool.link }}" target="_blank" class="btn btn-primary">GPT 실행하기 👉</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</body>
</html>
"""

# ==========================================
# 4. 서버 로직 (라우팅)
# ==========================================
@app.route('/')
def home():
    return render_template_string(HTML_TEMPLATE, tools=gpt_tools)

@app.route('/login', methods=['POST'])
def login():
    if request.form.get('password') == ACCESS_PASSWORD:
        session['authenticated'] = True
        return redirect('/')
    return render_template_string(HTML_TEMPLATE, error="비밀번호가 틀렸습니다.", tools=gpt_tools)

@app.route('/logout', methods=['POST'])
def logout():
    session.clear()
    return redirect('/')

from google.colab.output import eval_js
if __name__ == '__main__':
    print("----------------------------------------------------------------")
    print("👇 아래 나오는 긴 주소를 클릭하세요 (이게 진짜 접속 주소입니다!)")
    # 5000번 포트를 외부로 열어주는 마법의 코드
    print(eval_js("google.colab.kernel.proxyPort(5000)"))
    print("----------------------------------------------------------------")

    app.run(host='0.0.0.0', port=5000)



